version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: showzy_db
      POSTGRES_USER: felix
      POSTGRES_PASSWORD: fellykabange13
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app  # Adjusted to match the Dockerfile WORKDIR
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
